export default [
  { name: 'Heating', id: 1 },
  { name: 'Hangers', id: 2 },
  { name: 'Washer', id: 3 },
  { name: 'TV', id: 4 },
  { name: 'Netflix', id: 5 },
  { name: 'Private Bathroom', id: 6 },
  { name: 'Private Living Room', id: 7 },
  { name: 'Iron', id: 8 },
  { name: 'Air conditioning', id: 9 },
  { name: 'Free WiFi', id: 10 },
  { name: 'A welcome gift on arrival', id: 11 },
  { name: 'Kitchen', id: 12 },
  { name: 'Dishes and Silverware', id: 13 },
  { name: 'Cooking basics', id: 14 },
  { name: 'Dish Washer', id: 15 },
  { name: 'Stove', id: 16 },
  { name: 'Fridge', id: 17 },
  { name: 'Hot Water', id: 18 },
  { name: 'Hair Dryer', id: 19 },
  { name: 'Shampoo', id: 20 },
  { name: 'Bathtub', id: 21 },
  { name: 'Private Entrance', id: 22 },
  { name: 'Free parking', id: 23 },
  { name: 'Elevator', id: 24 },
  { name: 'First Aid Kit', id: 25 },
  { name: 'Smoke Alarm', id: 26 },
  { name: 'Fire extinguisher', id: 27 },
];
